Sub options
nio-blocks/intercom pull request #4
Opened 2017-10-27 18:14 UTC by tyoungNIO

2017-10-27 19:25 UTC, cowleyk requested changes

2017-10-27 19:25 UTC, cowleyk commented on README.md
> +- **callback_url**: Your publicly accessible url that Intercom can POST notifications to,  if webhook is managed by block
Need to add these properties to the spec file too

2017-10-30 15:27 UTC, cowleyk approved these changes

2017-10-31 21:23 UTC, tyoungNIO commented
closing, will move changes to new block class

2017-10-31 21:23 UTC, closed without merging